import html
import itertools
import re

import gradio as gr

from shared.gradio import model_infos


_COUNTER = itertools.count()


SYSTEM_HELP = {
    "spatial_upsampling": {
        "title": "Spatial Upsampling",
        "markdown": """
Spatial Upsampling increases the output resolution of the Image / Video by the Scale Factor that has been chosen. New Pixels created will depend on the upsampling method:

### Lanczos
- Works: images and videos, generation and late postprocessing.
- Speed: very fast CPU resize.
- Memory: tiny VRAM impact, low RAM use.
- Quality: sharper than a basic resize, but may add ringing/aliasing, won't extrapolate lost details

### VAE Upscaling
- Works: generation-time images usable only with Wan / QWen.
- Speed: no extra time since it runs through the existing VAE path.
- Memory: VRAM peak is mostly uneffected.
- Quality: more details than Lanczos but quality of created details worse than PiD/FlashVSR.
- Caveat: image-only, not available as late postprocessing.

### FlashVSR
- Works: videos and images, generation and late postprocessing.
- Speed: may be very slow in its final VAE decoding phase with Full version (pick Tiny version in configuration tab for faster performance).
- Memory: quite well RAM/VRAM optimized but may saturate VRAM if output > 10k.
- Quality: learned detail recovery with good video temporal stability. Two Pass may reduce horizontal banding
- Caveat: requires SpargeAttn to be installed for best results.

### Flux / Flux2 VAE PiD
- Works: images generated by a compatible Flux, Flux2, or Z-Image pipeline. Upsampler directly integrated in VAE.
- Speed: runs a dedicated x4 diffusion upsampler can be quite slow if image input has already a high resolution.
- Memory: moderate VRAM/RAM use, but avoids VAE re-encoding because the latent already exists.
- Quality: strongest detail recovery since the matching latent is available.
- Caveat: image-only and x4 only.

### Flux / Flux2 / Qwen PiD
- Works: existing images in late postprocessing.
- Speed: slightly slower since VAE-encodes first, then runs PiD.
- Memory: high RAM/VRAM use; tiling reduces VRAM peaks for large targets.
- Quality: strong detail recovery but some slight information may be loss due to VAE encoding
- Caveat: image-only and x4 only. Qwen PiD requires PiD v1.5.

### Chain-of-Zoom
- Works: images, generation and late postprocessing.
- Speed: slow, each x2/x4 step runs a one step SD3 diffusion per tile plus a VLM prompt extraction per tile; x8/x16 chain several steps.
- Memory: heavy downloads (SD3 Medium + Qwen2.5 VL 3B); MMGP swaps the models in VRAM so peaks stay moderate.
- Quality: extreme magnification (up to x16) with text guided detail synthesis; invented details may diverge from the source at high zooms.
- Caveat: image-only, supported factors x2 / x4 / x8 / x16.
""",
    },
}


def get_model_prompt_help(model_def):
    model_def = model_def or {}
    return model_def.get("prompt_infos", model_def.get("promt_infos", None))


def _normalize_classes(value):
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return list(value)


def _ensure_component_target(component):
    elem_id = getattr(component, "elem_id", None)
    if not elem_id:
        elem_id = f"wangp-field-help-target-{next(_COUNTER)}"
        component.elem_id = elem_id
    classes = _normalize_classes(getattr(component, "elem_classes", None))
    if "wangp-field-help-target" not in classes:
        classes.append("wangp-field-help-target")
        component.elem_classes = classes
    return elem_id


def _resolve_help(help_id, *, title=None, markdown=None):
    if markdown is not None:
        return title or "Help", str(markdown)
    help_def = SYSTEM_HELP.get(str(help_id or ""))
    if isinstance(help_def, dict):
        return title or help_def.get("title", "Help"), str(help_def.get("markdown", ""))
    return title or "Help", str(help_def or "")


def _tool_button(kind, popup_id, title, icon):
    popup_id = str(popup_id or "").strip()
    title = str(title or "")
    open_attr = f" data-wangp-model-info-open='{html.escape(popup_id, quote=True)}'" if popup_id else ""
    hidden_attr = "" if popup_id else " aria-hidden='true' tabindex='-1'"
    return (
        f"<button type='button' class='wangp-context-tool wangp-context-tool-{html.escape(kind, quote=True)}' "
        f"title='{html.escape(title, quote=True)}' aria-label='{html.escape(title, quote=True)}'{open_attr}{hidden_attr}>{icon}</button>"
    )


def render_marker(elem_id, help_id, *, title=None, markdown=None, helper_popup_id=None, helper_title=None):
    title, markdown = _resolve_help(help_id, title=title, markdown=markdown)
    has_markdown = bool(str(markdown or "").strip())
    has_helper = bool(str(helper_popup_id or "").strip())
    if not has_markdown and not has_helper:
        return ""
    popup_html = ""
    popup_id = ""
    if has_markdown:
        popup_key = re.sub(r"[^A-Za-z0-9_-]", "-", f"{elem_id}-{help_id}").strip("-").lower()
        popup_id = f"wangp-field-help-{popup_key}"
        popup_html = model_infos.render_info_popup(popup_id, title, markdown, lazy=True)
    info_button = _tool_button("info", popup_id, title, "&#9432;")
    helper_button = _tool_button("helper", helper_popup_id if has_helper else "", helper_title or "Prompt Helper", "&#129668;")
    return (
        f"<span class='wangp-field-help-inline' data-wangp-field-help-for='{html.escape(elem_id, quote=True)}'>"
        f"{info_button}{helper_button}"
        "</span>"
        f"{popup_html}"
    )


def bind(component, help_id, *, title=None, markdown=None):
    elem_id = _ensure_component_target(component)
    marker = render_marker(elem_id, help_id, title=title, markdown=markdown)
    if not marker:
        return gr.HTML("", visible=False)
    return gr.HTML(marker, elem_classes=["wangp-field-help-inline-host"])


def render_model_prompt_marker(elem_id, model_type, model_def, prompt_id, *, helper_popup_id=None, helper_title=None):
    return render_model_prompt_tools("", elem_id, model_type, model_def, prompt_id, helper_popup_id=helper_popup_id, helper_title=helper_title)


def render_model_prompt_tools(label, elem_id, model_type, model_def, prompt_id, *, helper_popup_id=None, helper_title=None):
    infos = get_model_prompt_help(model_def)
    if isinstance(infos, (list, tuple)) and len(infos) >= 2:
        title, markdown = str(infos[0] or "Prompt Guidelines"), str(infos[1] or "")
    else:
        title, markdown = "Prompt Guidelines", str(infos or "")
    popup_html = ""
    popup_id = ""
    if markdown.strip():
        popup_key = re.sub(r"[^A-Za-z0-9_-]", "-", f"{elem_id}-prompt-{model_type or 'model'}-{prompt_id or 'prompt'}").strip("-").lower()
        popup_id = f"wangp-field-help-{popup_key}"
        popup_html = model_infos.render_info_popup(popup_id, title, markdown, lazy=True)
    info_button = _tool_button("info", popup_id, title, "&#9432;")
    helper_button = _tool_button("helper", helper_popup_id, helper_title or "Prompt Helper", "&#129668;")
    row_class = "wangp-prompt-tools-row" if popup_id or str(helper_popup_id or "").strip() else "wangp-prompt-tools-row wangp-prompt-tools-empty"
    return (
        f"<div class='{row_class}' data-wangp-prompt-tools-for='{html.escape(elem_id, quote=True)}'>"
        f"<span class='wangp-context-tools'>{info_button}{helper_button}</span>"
        "</div>"
        f"{popup_html}"
    )


def get_css():
    return """
.wangp-prompt-tools-stack {
    position: relative;
}
.wangp-prompt-tools-anchor {
    position: absolute !important;
    left: 0 !important;
    top: 0 !important;
    width: 0 !important;
    min-height: 0 !important;
    height: 0 !important;
    margin: 0 !important;
    padding: 0 !important;
    border: 0 !important;
    background: transparent !important;
    overflow: visible !important;
}
.wangp-prompt-tools-anchor > :not(.wangp-model-info-popup):not([data-wangp-model-info-popup]),
.wangp-prompt-tools-anchor .html-container {
    min-height: 0 !important;
    height: 0 !important;
    margin: 0 !important;
    padding: 0 !important;
    border: 0 !important;
    background: transparent !important;
    overflow: visible !important;
}
.wangp-prompt-tools-anchor .wangp-prompt-tools-row {
    display: none !important;
}
.wangp-prompt-tools-row {
    display: inline-flex !important;
    align-items: center;
    gap: 4px;
    margin: -2px 0 -2px 6px;
    vertical-align: middle;
    line-height: 0 !important;
}
.wangp-prompt-tools-empty {
    display: none !important;
    margin: 0 !important;
}
.wangp-context-tools,
.wangp-field-help-inline {
    display: inline-flex !important;
    align-items: center;
    gap: 4px;
    vertical-align: middle;
    white-space: nowrap;
    margin-block: -2px !important;
    line-height: 0 !important;
}
.wangp-field-help-inline-host,
.wangp-field-help-inline-host > *,
.wangp-field-help-inline-host .html-container {
    position: absolute !important;
    left: 0 !important;
    top: 0 !important;
    width: 0 !important;
    min-height: 0 !important;
    height: 0 !important;
    margin: 0 !important;
    padding: 0 !important;
    border: 0 !important;
    background: transparent !important;
    overflow: visible !important;
}
.wangp-context-tool {
    position: static !important;
    display: inline-flex !important;
    align-items: center;
    justify-content: center;
    width: 18px !important;
    height: 18px !important;
    min-width: 18px !important;
    min-height: 18px !important;
    padding: 0 !important;
    margin: 0 !important;
    border: 1px solid var(--button-secondary-border-color, rgba(17, 84, 118, 0.24)) !important;
    border-radius: 999px !important;
    background: var(--button-secondary-background-fill, rgba(255, 255, 255, 0.86)) !important;
    color: var(--button-secondary-text-color, #155574) !important;
    box-shadow: none !important;
    cursor: pointer;
    vertical-align: middle;
    font-size: 11px !important;
    line-height: 1 !important;
    overflow: hidden !important;
    opacity: 1 !important;
    visibility: visible !important;
}
.wangp-context-tool:not([data-wangp-model-info-open]) {
    display: none !important;
}
.wangp-context-tool-helper {
    border: 1px solid var(--button-secondary-border-color, rgba(118, 74, 17, 0.26)) !important;
    color: var(--button-secondary-text-color, #7a520c) !important;
}
"""


def get_javascript():
    return """
    window.wangpPromptTools = window.wangpPromptTools || {};
    window.wangpPromptTools.attach = function(root) {
        const scope = root && root.querySelectorAll ? root : document;
        function movePopups(sourceRoot, buttons) {
            buttons.forEach((button) => {
                const popupId = button.getAttribute("data-wangp-model-info-open");
                if (!popupId) return;
                const popups = Array.from(document.querySelectorAll("[id]")).filter((popup) => popup.id === popupId);
                const popup = popups.find((candidate) => sourceRoot?.contains(candidate)) || popups[popups.length - 1];
                popups.forEach((candidate) => {
                    if (candidate !== popup) candidate.remove();
                });
                if (popup && popup.parentElement !== document.body) document.body.appendChild(popup);
            });
        }
        scope.querySelectorAll(".wangp-prompt-tools-row[data-wangp-prompt-tools-for]").forEach((row) => {
            if (!row.isConnected) return;
            const sourceRoot = row.parentElement;
            const targetId = row.getAttribute("data-wangp-prompt-tools-for") || "";
            const target = document.getElementById(targetId);
            const label = target?.querySelector('[data-testid="block-info"]');
            if (!label) return;
            movePopups(sourceRoot, row.querySelectorAll("[data-wangp-model-info-open]"));
            label.querySelectorAll(".wangp-prompt-tools-row[data-wangp-prompt-tools-for]").forEach((existing) => {
                if (existing !== row && existing.getAttribute("data-wangp-prompt-tools-for") === targetId) existing.remove();
            });
            if (row.isConnected && row.parentElement !== label) label.appendChild(row);
        });
        scope.querySelectorAll(".wangp-field-help-inline[data-wangp-field-help-for]").forEach((inline) => {
            if (!inline.isConnected) return;
            const sourceRoot = inline.parentElement;
            const targetId = inline.getAttribute("data-wangp-field-help-for") || "";
            const target = document.getElementById(targetId);
            const label = target?.querySelector('[data-testid="block-info"]');
            if (!label) return;
            movePopups(sourceRoot, inline.querySelectorAll("[data-wangp-model-info-open]"));
            label.querySelectorAll(".wangp-field-help-inline[data-wangp-field-help-for]").forEach((existing) => {
                if (existing !== inline && existing.getAttribute("data-wangp-field-help-for") === targetId) existing.remove();
            });
            if (inline.isConnected && inline.parentElement !== label) label.appendChild(inline);
        });
    };
"""
